apiVersion: supply-chain.apps.tanzu.vmware.com/v1alpha1
kind: SupplyChain
metadata:
    name: statefulsetappv1
spec:
    defines:
        group: supplychains.pve.tanzu.vmware.com
        kind: StatefulSetAppV1
        plural: statefulsetappv1s
        version: v1alpha1
    description: Supply Chain that produces a statefulset
    stages:
        - componentRef:
            name: source-git-provider-1.0.0
          name: source-git-provider
        - componentRef:
            name: buildpack-build-1.0.0
          name: buildpack-build
        - componentRef:
            name: conventions-1.0.0
          name: conventions
        - componentRef:
            name: app-config-web-1.0.0
          name: app-config-web
        - componentRef:
            name: carvel-package-1.0.0
          name: carvel-package
        - componentRef:
            name: git-writer-1.0.0
          name: git-writer
